# Machine Learning
### IFX-41-GAB02<br>Akbar Habib Buana Wibawa Putra<br>1301178198
#### Tugas 0A - TelU Legends Heroes

# Bumi Terancam Punah... Tapi Belum Terlambat untuk Menyelamatkannya!

Dunia sedang dalam krisis yang gawat. Serangan demi serangan merajalela.

<img src="https://raw.githubusercontent.com/machine-learning-course/syllabus/gh-pages/exercise-0a/villain.jpg">

Beberapa <i>heroes</i> dengan gagah berani maju ke depan untuk menyelamatkan dunia. Namun...

Kita punya masalah besar! Tidak ada orang yang dapat mengetahui, apa peran masing-masing <i>hero</i> dalam menyelamatkan dunia.

Dunia membutuhkan bantuan dari Anda, wahai mahasiswa Teknik Informatika Telkom University. yang dahsyat dan penuh semangat. Dunia membutuhkan karya Anda... <b>Heroes Classifier</b>!

### Heroes Membutuhkan Anda

Setiap <i>heroes</i> akan mengisi formulir biodata <i>hero</i>, dalam file teks bernama <code>test.csv</code> dengan struktur CSV

In [1]:
#import panda untuk mempermudah membaca file .csv
import pandas as pd

In [2]:
#membaca file test.csv dan menampilkan datanya
test_df = pd.read_csv("Downloads/test.csv")
test_df

name  movementSpeed  physicalAttack  armor    hp  mana
0         Layla            270             118     15  2500   424
1       Cyclops            250             107     18  2461   500
2      Minotaur            265             123     25  2705     0
3         Saber            265             121     17  2475   443
4         Roger            235             120     22  2580   450
5          Nana            250             110     17  2325   499
6          Akai            260             115     24  2769   422
7         Alice            240             109     21  2397   493
8         Alpha            236             121     20  2646   453
9       Alucard            265             118     21  2593     0
10        Argus            260             124     21  2628     0
11       Aurora            245             105     17  2441   500
12      Balmond            265             114     23  2602     0
13         Bane            265             117     23  2625   433
14        Bruno            240             116     17  2402   439
15         Chou            265             121     23  2598     0
16        Clint            248             122     20  2500   450
17       Diggie            250             115     16  2351   490
18        Estes            240             115     13  2161   545
19       Eudora            250             112     19  2524   468
20        Fanny            270             126     17  2402     0
21       Franco            255             116     25  2575   440
22        Freya            265             109     22  2673   462
23    Gatotkaca            260             120     20  2709   440
24         Gord            240             105     13  2302   570
25        Grock            260             135     21  2819   430
26       Harley            240             114     19  2501   490
27     Hayabusa            265             114     17  2555   479
28       Helcur            255             121     17  2599   440
29        Hilda            260             123     24  2909     0
30        Hylos            260             105     17  3309   430
31      Irithel            250             110     17  2540   438
32      Johnson            255             112     27  2809     0
33       Kagura            240             113     19  2380   519
34       Karina            265             121     20  2505   431
35       Karrie            240             112     17  2498   440
36     Lancelot            260             124     16  2546   450
37    Lapu-lapu            260             119     21  2628     0
38       Lolita            265             115     27  2545     0
39         Miya            235             114     17  2404   445
40       Moskov            240             125     16  2530   420
41      Natalia            265             121     18  2465   486
42       Odette            240             105     18  2491   495
43       Pharsa            240             109     15  2421   490
44      Rafaela            245             112     15  2265   545
45         Ruby            265             114     23  2709   430
46   Sun Wukong            265             114     23  2630   400
47      Tigreal            265             112     25  2756   450
48       Vexana            245             112     17  2421   490
49  Yi Sun-Shin            240             110     18  2520   438
50     Yun Zhao            270             123     25  2561   405
51        Zhask            240             107     15  2401   490

Misi Anda adalah menentukan, apa peran dari masing-masing hero yang membutuhkan bantuan dari program Anda, dengan aturan sebagai berikut secara berurutan (hero mendapatkan peran yang <b>paling awal</b> memenuhi syarat):
1. Heroes yang memiliki <b>movementSpeed</b> >= 270, akan mendapat peran sebagai <b>MARKSMAN</b> (huruf kapital semua)
2. Heroes dengan <b>mana</b> >= 500, akan mendapat peran sebagai <b>MAGE</b> (huruf kapital semua)
3. Heroes dengan <b>armor</b> >= 25, akan mendapat peran sebagai <b>TANK</b> (huruf kapital semua)
4. Heroes dengan <b>physicalAttack</b> >= 121, akan mendapat peran sebagai <b>ASSASSIN</b> (huruf kapital semua)
5. Heroes dengan <b>hp</b> >= 2580, akan mendapat peran sebagai <b>FIGHTER</b> (huruf kapital semua)
6. Heroes lainnya akan mendapat peran sebagai <b>SUPPORT</b> (huruf kapital semua)


In [3]:
#variabel untuk menyimpan peran hero
kelas = []

Selanjutnya buat fungsi untuk mengklasifikasikan hero berdasarkan status hero sesuai aturan diatas

In [4]:
for data in range(len(test_df)) :
    if test_df["movementSpeed"][data] >= 270:
        kelas.append("MARKSMAN")
    elif test_df["mana"][data] >= 500:
        kelas.append("MAGE")
    elif test_df["armor"][data] >= 25:
        kelas.append("TANK")
    elif test_df["physicalAttack"][data] >= 121:
        kelas.append("ASSASSIN")
    elif test_df["hp"][data] >= 2580:
        kelas.append("FIGHTER")
    else: kelas.append("SUPPORT")

Langkah selanjutnya adalah gabungkan nama-nama hero dan perannya masing masing kedalam sebuah data frame baru

In [5]:
prediksi = pd.DataFrame({
    "name" : test_df["name"],
    "role" : kelas
})

Kemudian hasilnya dikeluarkan ke file prediction.csv

In [6]:
prediksi.to_csv("prediction.csv", index = False)

Selesai!

# <center>Sekian</center>